server:
  port: 8081
  servlet:
    context-path: /luckmoney

limit:
  minMoney: 1
  maxMoney: 200
  description: 最少要${limit.minMoney}元,最多${limit.maxMoney}
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_ai?useSSL=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: 9631
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
